global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'control-plane'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'

  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'

  - job_name: 'hot-tier'
    static_configs:
      - targets: 
        - 'host.docker.internal:8090'
        - 'host.docker.internal:8091'
        - 'host.docker.internal:8092'
    metrics_path: '/metrics'

  - job_name: 'query-api'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/metrics'

  - job_name: 'stream-ingester'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/metrics'

  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']