// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterOperator int32

const (
	FilterOperator_EQUALS                 FilterOperator = 0
	FilterOperator_NOT_EQUALS             FilterOperator = 1
	FilterOperator_LESS_THAN              FilterOperator = 2
	FilterOperator_LESS_THAN_OR_EQUALS    FilterOperator = 3
	FilterOperator_GREATER_THAN           FilterOperator = 4
	FilterOperator_GREATER_THAN_OR_EQUALS FilterOperator = 5
	FilterOperator_IN                     FilterOperator = 6
	FilterOperator_NOT_IN                 FilterOperator = 7
	FilterOperator_CONTAINS               FilterOperator = 8
	FilterOperator_NOT_CONTAINS           FilterOperator = 9
	FilterOperator_IS_NULL                FilterOperator = 10
	FilterOperator_IS_NOT_NULL            FilterOperator = 11
)

// Enum value maps for FilterOperator.
var (
	FilterOperator_name = map[int32]string{
		0:  "EQUALS",
		1:  "NOT_EQUALS",
		2:  "LESS_THAN",
		3:  "LESS_THAN_OR_EQUALS",
		4:  "GREATER_THAN",
		5:  "GREATER_THAN_OR_EQUALS",
		6:  "IN",
		7:  "NOT_IN",
		8:  "CONTAINS",
		9:  "NOT_CONTAINS",
		10: "IS_NULL",
		11: "IS_NOT_NULL",
	}
	FilterOperator_value = map[string]int32{
		"EQUALS":                 0,
		"NOT_EQUALS":             1,
		"LESS_THAN":              2,
		"LESS_THAN_OR_EQUALS":    3,
		"GREATER_THAN":           4,
		"GREATER_THAN_OR_EQUALS": 5,
		"IN":                     6,
		"NOT_IN":                 7,
		"CONTAINS":               8,
		"NOT_CONTAINS":           9,
		"IS_NULL":                10,
		"IS_NOT_NULL":            11,
	}
)

func (x FilterOperator) Enum() *FilterOperator {
	p := new(FilterOperator)
	*p = x
	return p
}

func (x FilterOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[0].Descriptor()
}

func (FilterOperator) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[0]
}

func (x FilterOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterOperator.Descriptor instead.
func (FilterOperator) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

type QueryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	QueryId   string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"` // Client-provided unique ID
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table     string                 `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	// Time range
	StartTimeMs int64 `protobuf:"varint,4,opt,name=start_time_ms,json=startTimeMs,proto3" json:"start_time_ms,omitempty"`
	EndTimeMs   int64 `protobuf:"varint,5,opt,name=end_time_ms,json=endTimeMs,proto3" json:"end_time_ms,omitempty"`
	// Aggregations
	Aggregations []*Aggregation `protobuf:"bytes,6,rep,name=aggregations,proto3" json:"aggregations,omitempty"`
	// Filters
	Filters []*Filter `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty"`
	// Group by
	GroupBy []string `protobuf:"bytes,8,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	// Order by
	OrderBy []*OrderBy `protobuf:"bytes,9,rep,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	// Pagination
	Limit  int32 `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	// Query options
	Options       *QueryOptions `protobuf:"bytes,12,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *QueryRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *QueryRequest) GetStartTimeMs() int64 {
	if x != nil {
		return x.StartTimeMs
	}
	return 0
}

func (x *QueryRequest) GetEndTimeMs() int64 {
	if x != nil {
		return x.EndTimeMs
	}
	return 0
}

func (x *QueryRequest) GetAggregations() []*Aggregation {
	if x != nil {
		return x.Aggregations
	}
	return nil
}

func (x *QueryRequest) GetFilters() []*Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *QueryRequest) GetGroupBy() []string {
	if x != nil {
		return x.GroupBy
	}
	return nil
}

func (x *QueryRequest) GetOrderBy() []*OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return nil
}

func (x *QueryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type Aggregation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"` // "count", "sum", "avg", "min", "max", "p50", "p95", "p99", "unique"
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Alias         string                 `protobuf:"bytes,3,opt,name=alias,proto3" json:"alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aggregation) Reset() {
	*x = Aggregation{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggregation) ProtoMessage() {}

func (x *Aggregation) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggregation.ProtoReflect.Descriptor instead.
func (*Aggregation) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *Aggregation) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *Aggregation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Aggregation) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator      FilterOperator         `protobuf:"varint,2,opt,name=operator,proto3,enum=truenow.query.FilterOperator" json:"operator,omitempty"`
	Value         *structpb.Value        `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Values        []*structpb.Value      `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"` // For IN operator
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Filter) GetOperator() FilterOperator {
	if x != nil {
		return x.Operator
	}
	return FilterOperator_EQUALS
}

func (x *Filter) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Filter) GetValues() []*structpb.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type OrderBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Descending    bool                   `protobuf:"varint,2,opt,name=descending,proto3" json:"descending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBy) Reset() {
	*x = OrderBy{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBy) ProtoMessage() {}

func (x *OrderBy) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBy.ProtoReflect.Descriptor instead.
func (*OrderBy) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *OrderBy) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *OrderBy) GetDescending() bool {
	if x != nil {
		return x.Descending
	}
	return false
}

type QueryOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UseCache        bool                   `protobuf:"varint,1,opt,name=use_cache,json=useCache,proto3" json:"use_cache,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	Approximate     bool                   `protobuf:"varint,3,opt,name=approximate,proto3" json:"approximate,omitempty"`                       // Allow approximate results for better performance
	SamplingRate    int32                  `protobuf:"varint,4,opt,name=sampling_rate,json=samplingRate,proto3" json:"sampling_rate,omitempty"` // 1-100, percentage of data to sample
	IncludeMetadata bool                   `protobuf:"varint,5,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryOptions) GetUseCache() bool {
	if x != nil {
		return x.UseCache
	}
	return false
}

func (x *QueryOptions) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *QueryOptions) GetApproximate() bool {
	if x != nil {
		return x.Approximate
	}
	return false
}

func (x *QueryOptions) GetSamplingRate() int32 {
	if x != nil {
		return x.SamplingRate
	}
	return 0
}

func (x *QueryOptions) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Results       []*QueryResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	Metadata      *QueryMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *QueryResponse) GetMetadata() *QueryMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *QueryResponse) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

type QueryResult struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Row           map[string]*structpb.Value `protobuf:"bytes,1,rep,name=row,proto3" json:"row,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                      `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryResult) GetRow() map[string]*structpb.Value {
	if x != nil {
		return x.Row
	}
	return nil
}

func (x *QueryResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type QueryMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalRows       int64                  `protobuf:"varint,1,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	RowsScanned     int64                  `protobuf:"varint,2,opt,name=rows_scanned,json=rowsScanned,proto3" json:"rows_scanned,omitempty"`
	BytesScanned    int64                  `protobuf:"varint,3,opt,name=bytes_scanned,json=bytesScanned,proto3" json:"bytes_scanned,omitempty"`
	ExecutionTimeMs float64                `protobuf:"fixed64,4,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	QueueTimeMs     float64                `protobuf:"fixed64,5,opt,name=queue_time_ms,json=queueTimeMs,proto3" json:"queue_time_ms,omitempty"`
	ShardsQueried   int32                  `protobuf:"varint,6,opt,name=shards_queried,json=shardsQueried,proto3" json:"shards_queried,omitempty"`
	FromCache       bool                   `protobuf:"varint,7,opt,name=from_cache,json=fromCache,proto3" json:"from_cache,omitempty"`
	Truncated       bool                   `protobuf:"varint,8,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Warnings        []string               `protobuf:"bytes,9,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryMetadata) Reset() {
	*x = QueryMetadata{}
	mi := &file_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetadata) ProtoMessage() {}

func (x *QueryMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetadata.ProtoReflect.Descriptor instead.
func (*QueryMetadata) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryMetadata) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *QueryMetadata) GetRowsScanned() int64 {
	if x != nil {
		return x.RowsScanned
	}
	return 0
}

func (x *QueryMetadata) GetBytesScanned() int64 {
	if x != nil {
		return x.BytesScanned
	}
	return 0
}

func (x *QueryMetadata) GetExecutionTimeMs() float64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *QueryMetadata) GetQueueTimeMs() float64 {
	if x != nil {
		return x.QueueTimeMs
	}
	return 0
}

func (x *QueryMetadata) GetShardsQueried() int32 {
	if x != nil {
		return x.ShardsQueried
	}
	return 0
}

func (x *QueryMetadata) GetFromCache() bool {
	if x != nil {
		return x.FromCache
	}
	return false
}

func (x *QueryMetadata) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *QueryMetadata) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ExplainQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *QueryRequest          `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Verbose       bool                   `protobuf:"varint,2,opt,name=verbose,proto3" json:"verbose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainQueryRequest) Reset() {
	*x = ExplainQueryRequest{}
	mi := &file_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainQueryRequest) ProtoMessage() {}

func (x *ExplainQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainQueryRequest.ProtoReflect.Descriptor instead.
func (*ExplainQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{8}
}

func (x *ExplainQueryRequest) GetQuery() *QueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ExplainQueryRequest) GetVerbose() bool {
	if x != nil {
		return x.Verbose
	}
	return false
}

type ExplainQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plan          *QueryPlan             `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	EstimatedCost float64                `protobuf:"fixed64,2,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	EstimatedRows int64                  `protobuf:"varint,3,opt,name=estimated_rows,json=estimatedRows,proto3" json:"estimated_rows,omitempty"`
	Optimizations []string               `protobuf:"bytes,4,rep,name=optimizations,proto3" json:"optimizations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainQueryResponse) Reset() {
	*x = ExplainQueryResponse{}
	mi := &file_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainQueryResponse) ProtoMessage() {}

func (x *ExplainQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainQueryResponse.ProtoReflect.Descriptor instead.
func (*ExplainQueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{9}
}

func (x *ExplainQueryResponse) GetPlan() *QueryPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *ExplainQueryResponse) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *ExplainQueryResponse) GetEstimatedRows() int64 {
	if x != nil {
		return x.EstimatedRows
	}
	return 0
}

func (x *ExplainQueryResponse) GetOptimizations() []string {
	if x != nil {
		return x.Optimizations
	}
	return nil
}

type QueryPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "scan", "filter", "aggregate", "sort", "limit"
	Children      []*QueryPlan           `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EstimatedCost float64                `protobuf:"fixed64,4,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPlan) Reset() {
	*x = QueryPlan{}
	mi := &file_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlan) ProtoMessage() {}

func (x *QueryPlan) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlan.ProtoReflect.Descriptor instead.
func (*QueryPlan) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryPlan) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QueryPlan) GetChildren() []*QueryPlan {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *QueryPlan) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *QueryPlan) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"` // Optional, if empty returns all tables
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{11}
}

func (x *GetSchemaRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetSchemaRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tables        []*TableSchema         `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{12}
}

func (x *GetSchemaResponse) GetTables() []*TableSchema {
	if x != nil {
		return x.Tables
	}
	return nil
}

type TableSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Fields        []*FieldSchema         `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	RowCount      int64                  `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	mi := &file_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{13}
}

func (x *TableSchema) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TableSchema) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *TableSchema) GetFields() []*FieldSchema {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *TableSchema) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *TableSchema) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *TableSchema) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TableSchema) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type FieldSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "string", "int64", "float64", "bool", "timestamp"
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Indexed       bool                   `protobuf:"varint,4,opt,name=indexed,proto3" json:"indexed,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSchema) Reset() {
	*x = FieldSchema{}
	mi := &file_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSchema) ProtoMessage() {}

func (x *FieldSchema) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSchema.ProtoReflect.Descriptor instead.
func (*FieldSchema) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{14}
}

func (x *FieldSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldSchema) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *FieldSchema) GetIndexed() bool {
	if x != nil {
		return x.Indexed
	}
	return false
}

func (x *FieldSchema) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

type GetQueryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WindowSeconds int32                  `protobuf:"varint,1,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryStatsRequest) Reset() {
	*x = GetQueryStatsRequest{}
	mi := &file_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryStatsRequest) ProtoMessage() {}

func (x *GetQueryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryStatsRequest.ProtoReflect.Descriptor instead.
func (*GetQueryStatsRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{15}
}

func (x *GetQueryStatsRequest) GetWindowSeconds() int32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *GetQueryStatsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type QueryStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalQueries     int64                  `protobuf:"varint,1,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	QueriesPerSecond int64                  `protobuf:"varint,2,opt,name=queries_per_second,json=queriesPerSecond,proto3" json:"queries_per_second,omitempty"`
	AvgLatencyMs     float64                `protobuf:"fixed64,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P50LatencyMs     float64                `protobuf:"fixed64,4,opt,name=p50_latency_ms,json=p50LatencyMs,proto3" json:"p50_latency_ms,omitempty"`
	P95LatencyMs     float64                `protobuf:"fixed64,5,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs     float64                `protobuf:"fixed64,6,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	CacheHits        int64                  `protobuf:"varint,7,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses      int64                  `protobuf:"varint,8,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	CacheHitRate     float64                `protobuf:"fixed64,9,opt,name=cache_hit_rate,json=cacheHitRate,proto3" json:"cache_hit_rate,omitempty"`
	TopQueries       []*TopQuery            `protobuf:"bytes,10,rep,name=top_queries,json=topQueries,proto3" json:"top_queries,omitempty"`
	CalculatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryStatsResponse) Reset() {
	*x = QueryStatsResponse{}
	mi := &file_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatsResponse) ProtoMessage() {}

func (x *QueryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryStatsResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryStatsResponse) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *QueryStatsResponse) GetQueriesPerSecond() int64 {
	if x != nil {
		return x.QueriesPerSecond
	}
	return 0
}

func (x *QueryStatsResponse) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *QueryStatsResponse) GetP50LatencyMs() float64 {
	if x != nil {
		return x.P50LatencyMs
	}
	return 0
}

func (x *QueryStatsResponse) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *QueryStatsResponse) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

func (x *QueryStatsResponse) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *QueryStatsResponse) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *QueryStatsResponse) GetCacheHitRate() float64 {
	if x != nil {
		return x.CacheHitRate
	}
	return 0
}

func (x *QueryStatsResponse) GetTopQueries() []*TopQuery {
	if x != nil {
		return x.TopQueries
	}
	return nil
}

func (x *QueryStatsResponse) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

type TopQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryPattern  string                 `protobuf:"bytes,1,opt,name=query_pattern,json=queryPattern,proto3" json:"query_pattern,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,3,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	TotalRows     int64                  `protobuf:"varint,4,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopQuery) Reset() {
	*x = TopQuery{}
	mi := &file_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopQuery) ProtoMessage() {}

func (x *TopQuery) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopQuery.ProtoReflect.Descriptor instead.
func (*TopQuery) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{17}
}

func (x *TopQuery) GetQueryPattern() string {
	if x != nil {
		return x.QueryPattern
	}
	return ""
}

func (x *TopQuery) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TopQuery) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *TopQuery) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

type CancelQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryRequest) Reset() {
	*x = CancelQueryRequest{}
	mi := &file_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryRequest) ProtoMessage() {}

func (x *CancelQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryRequest.ProtoReflect.Descriptor instead.
func (*CancelQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{18}
}

func (x *CancelQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *CancelQueryRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryResponse) Reset() {
	*x = CancelQueryResponse{}
	mi := &file_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryResponse) ProtoMessage() {}

func (x *CancelQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryResponse.ProtoReflect.Descriptor instead.
func (*CancelQueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{19}
}

func (x *CancelQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\rtruenow.query\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc5\x03\n" +
	"\fQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05table\x18\x03 \x01(\tR\x05table\x12\"\n" +
	"\rstart_time_ms\x18\x04 \x01(\x03R\vstartTimeMs\x12\x1e\n" +
	"\vend_time_ms\x18\x05 \x01(\x03R\tendTimeMs\x12>\n" +
	"\faggregations\x18\x06 \x03(\v2\x1a.truenow.query.AggregationR\faggregations\x12/\n" +
	"\afilters\x18\a \x03(\v2\x15.truenow.query.FilterR\afilters\x12\x19\n" +
	"\bgroup_by\x18\b \x03(\tR\agroupBy\x121\n" +
	"\border_by\x18\t \x03(\v2\x16.truenow.query.OrderByR\aorderBy\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\v \x01(\x05R\x06offset\x125\n" +
	"\aoptions\x18\f \x01(\v2\x1b.truenow.query.QueryOptionsR\aoptions\"U\n" +
	"\vAggregation\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05alias\x18\x03 \x01(\tR\x05alias\"\xb7\x01\n" +
	"\x06Filter\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x129\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1d.truenow.query.FilterOperatorR\boperator\x12,\n" +
	"\x05value\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x05value\x12.\n" +
	"\x06values\x18\x04 \x03(\v2\x16.google.protobuf.ValueR\x06values\"?\n" +
	"\aOrderBy\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1e\n" +
	"\n" +
	"descending\x18\x02 \x01(\bR\n" +
	"descending\"\xc6\x01\n" +
	"\fQueryOptions\x12\x1b\n" +
	"\tuse_cache\x18\x01 \x01(\bR\buseCache\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12 \n" +
	"\vapproximate\x18\x03 \x01(\bR\vapproximate\x12#\n" +
	"\rsampling_rate\x18\x04 \x01(\x05R\fsamplingRate\x12)\n" +
	"\x10include_metadata\x18\x05 \x01(\bR\x0fincludeMetadata\"\xd7\x01\n" +
	"\rQueryResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x124\n" +
	"\aresults\x18\x02 \x03(\v2\x1a.truenow.query.QueryResultR\aresults\x128\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1c.truenow.query.QueryMetadataR\bmetadata\x12;\n" +
	"\vexecuted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt\"\xb2\x01\n" +
	"\vQueryResult\x125\n" +
	"\x03row\x18\x01 \x03(\v2#.truenow.query.QueryResult.RowEntryR\x03row\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x1aN\n" +
	"\bRowEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xc6\x02\n" +
	"\rQueryMetadata\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x01 \x01(\x03R\ttotalRows\x12!\n" +
	"\frows_scanned\x18\x02 \x01(\x03R\vrowsScanned\x12#\n" +
	"\rbytes_scanned\x18\x03 \x01(\x03R\fbytesScanned\x12*\n" +
	"\x11execution_time_ms\x18\x04 \x01(\x01R\x0fexecutionTimeMs\x12\"\n" +
	"\rqueue_time_ms\x18\x05 \x01(\x01R\vqueueTimeMs\x12%\n" +
	"\x0eshards_queried\x18\x06 \x01(\x05R\rshardsQueried\x12\x1d\n" +
	"\n" +
	"from_cache\x18\a \x01(\bR\tfromCache\x12\x1c\n" +
	"\ttruncated\x18\b \x01(\bR\ttruncated\x12\x1a\n" +
	"\bwarnings\x18\t \x03(\tR\bwarnings\"b\n" +
	"\x13ExplainQueryRequest\x121\n" +
	"\x05query\x18\x01 \x01(\v2\x1b.truenow.query.QueryRequestR\x05query\x12\x18\n" +
	"\averbose\x18\x02 \x01(\bR\averbose\"\xb8\x01\n" +
	"\x14ExplainQueryResponse\x12,\n" +
	"\x04plan\x18\x01 \x01(\v2\x18.truenow.query.QueryPlanR\x04plan\x12%\n" +
	"\x0eestimated_cost\x18\x02 \x01(\x01R\restimatedCost\x12%\n" +
	"\x0eestimated_rows\x18\x03 \x01(\x03R\restimatedRows\x12$\n" +
	"\roptimizations\x18\x04 \x03(\tR\roptimizations\"\x85\x02\n" +
	"\tQueryPlan\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\bchildren\x18\x02 \x03(\v2\x18.truenow.query.QueryPlanR\bchildren\x12H\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2(.truenow.query.QueryPlan.PropertiesEntryR\n" +
	"properties\x12%\n" +
	"\x0eestimated_cost\x18\x04 \x01(\x01R\restimatedCost\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x10GetSchemaRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\"G\n" +
	"\x11GetSchemaResponse\x122\n" +
	"\x06tables\x18\x01 \x03(\v2\x1a.truenow.query.TableSchemaR\x06tables\"\xa7\x02\n" +
	"\vTableSchema\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x122\n" +
	"\x06fields\x18\x03 \x03(\v2\x1a.truenow.query.FieldSchemaR\x06fields\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x03R\browCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf6\x01\n" +
	"\vFieldSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x18\n" +
	"\aindexed\x18\x04 \x01(\bR\aindexed\x12J\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2*.truenow.query.FieldSchema.PropertiesEntryR\n" +
	"properties\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x14GetQueryStatsRequest\x12%\n" +
	"\x0ewindow_seconds\x18\x01 \x01(\x05R\rwindowSeconds\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xe2\x03\n" +
	"\x12QueryStatsResponse\x12#\n" +
	"\rtotal_queries\x18\x01 \x01(\x03R\ftotalQueries\x12,\n" +
	"\x12queries_per_second\x18\x02 \x01(\x03R\x10queriesPerSecond\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep50_latency_ms\x18\x04 \x01(\x01R\fp50LatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x05 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x06 \x01(\x01R\fp99LatencyMs\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\a \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\b \x01(\x03R\vcacheMisses\x12$\n" +
	"\x0ecache_hit_rate\x18\t \x01(\x01R\fcacheHitRate\x128\n" +
	"\vtop_queries\x18\n" +
	" \x03(\v2\x17.truenow.query.TopQueryR\n" +
	"topQueries\x12?\n" +
	"\rcalculated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\"\x8a\x01\n" +
	"\bTopQuery\x12#\n" +
	"\rquery_pattern\x18\x01 \x01(\tR\fqueryPattern\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12$\n" +
	"\x0eavg_latency_ms\x18\x03 \x01(\x01R\favgLatencyMs\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x04 \x01(\x03R\ttotalRows\"G\n" +
	"\x12CancelQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"I\n" +
	"\x13CancelQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xd4\x01\n" +
	"\x0eFilterOperator\x12\n" +
	"\n" +
	"\x06EQUALS\x10\x00\x12\x0e\n" +
	"\n" +
	"NOT_EQUALS\x10\x01\x12\r\n" +
	"\tLESS_THAN\x10\x02\x12\x17\n" +
	"\x13LESS_THAN_OR_EQUALS\x10\x03\x12\x10\n" +
	"\fGREATER_THAN\x10\x04\x12\x1a\n" +
	"\x16GREATER_THAN_OR_EQUALS\x10\x05\x12\x06\n" +
	"\x02IN\x10\x06\x12\n" +
	"\n" +
	"\x06NOT_IN\x10\a\x12\f\n" +
	"\bCONTAINS\x10\b\x12\x10\n" +
	"\fNOT_CONTAINS\x10\t\x12\v\n" +
	"\aIS_NULL\x10\n" +
	"\x12\x0f\n" +
	"\vIS_NOT_NULL\x10\v2\xfb\x03\n" +
	"\fQueryService\x12I\n" +
	"\fExecuteQuery\x12\x1b.truenow.query.QueryRequest\x1a\x1c.truenow.query.QueryResponse\x12H\n" +
	"\vStreamQuery\x12\x1b.truenow.query.QueryRequest\x1a\x1a.truenow.query.QueryResult0\x01\x12W\n" +
	"\fExplainQuery\x12\".truenow.query.ExplainQueryRequest\x1a#.truenow.query.ExplainQueryResponse\x12N\n" +
	"\tGetSchema\x12\x1f.truenow.query.GetSchemaRequest\x1a .truenow.query.GetSchemaResponse\x12W\n" +
	"\rGetQueryStats\x12#.truenow.query.GetQueryStatsRequest\x1a!.truenow.query.QueryStatsResponse\x12T\n" +
	"\vCancelQuery\x12!.truenow.query.CancelQueryRequest\x1a\".truenow.query.CancelQueryResponseB4Z2github.com/Milad-Afdasta/TrueNow/proto/query;queryb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_query_proto_goTypes = []any{
	(FilterOperator)(0),           // 0: truenow.query.FilterOperator
	(*QueryRequest)(nil),          // 1: truenow.query.QueryRequest
	(*Aggregation)(nil),           // 2: truenow.query.Aggregation
	(*Filter)(nil),                // 3: truenow.query.Filter
	(*OrderBy)(nil),               // 4: truenow.query.OrderBy
	(*QueryOptions)(nil),          // 5: truenow.query.QueryOptions
	(*QueryResponse)(nil),         // 6: truenow.query.QueryResponse
	(*QueryResult)(nil),           // 7: truenow.query.QueryResult
	(*QueryMetadata)(nil),         // 8: truenow.query.QueryMetadata
	(*ExplainQueryRequest)(nil),   // 9: truenow.query.ExplainQueryRequest
	(*ExplainQueryResponse)(nil),  // 10: truenow.query.ExplainQueryResponse
	(*QueryPlan)(nil),             // 11: truenow.query.QueryPlan
	(*GetSchemaRequest)(nil),      // 12: truenow.query.GetSchemaRequest
	(*GetSchemaResponse)(nil),     // 13: truenow.query.GetSchemaResponse
	(*TableSchema)(nil),           // 14: truenow.query.TableSchema
	(*FieldSchema)(nil),           // 15: truenow.query.FieldSchema
	(*GetQueryStatsRequest)(nil),  // 16: truenow.query.GetQueryStatsRequest
	(*QueryStatsResponse)(nil),    // 17: truenow.query.QueryStatsResponse
	(*TopQuery)(nil),              // 18: truenow.query.TopQuery
	(*CancelQueryRequest)(nil),    // 19: truenow.query.CancelQueryRequest
	(*CancelQueryResponse)(nil),   // 20: truenow.query.CancelQueryResponse
	nil,                           // 21: truenow.query.QueryResult.RowEntry
	nil,                           // 22: truenow.query.QueryPlan.PropertiesEntry
	nil,                           // 23: truenow.query.FieldSchema.PropertiesEntry
	(*structpb.Value)(nil),        // 24: google.protobuf.Value
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
}
var file_query_proto_depIdxs = []int32{
	2,  // 0: truenow.query.QueryRequest.aggregations:type_name -> truenow.query.Aggregation
	3,  // 1: truenow.query.QueryRequest.filters:type_name -> truenow.query.Filter
	4,  // 2: truenow.query.QueryRequest.order_by:type_name -> truenow.query.OrderBy
	5,  // 3: truenow.query.QueryRequest.options:type_name -> truenow.query.QueryOptions
	0,  // 4: truenow.query.Filter.operator:type_name -> truenow.query.FilterOperator
	24, // 5: truenow.query.Filter.value:type_name -> google.protobuf.Value
	24, // 6: truenow.query.Filter.values:type_name -> google.protobuf.Value
	7,  // 7: truenow.query.QueryResponse.results:type_name -> truenow.query.QueryResult
	8,  // 8: truenow.query.QueryResponse.metadata:type_name -> truenow.query.QueryMetadata
	25, // 9: truenow.query.QueryResponse.executed_at:type_name -> google.protobuf.Timestamp
	21, // 10: truenow.query.QueryResult.row:type_name -> truenow.query.QueryResult.RowEntry
	1,  // 11: truenow.query.ExplainQueryRequest.query:type_name -> truenow.query.QueryRequest
	11, // 12: truenow.query.ExplainQueryResponse.plan:type_name -> truenow.query.QueryPlan
	11, // 13: truenow.query.QueryPlan.children:type_name -> truenow.query.QueryPlan
	22, // 14: truenow.query.QueryPlan.properties:type_name -> truenow.query.QueryPlan.PropertiesEntry
	14, // 15: truenow.query.GetSchemaResponse.tables:type_name -> truenow.query.TableSchema
	15, // 16: truenow.query.TableSchema.fields:type_name -> truenow.query.FieldSchema
	25, // 17: truenow.query.TableSchema.created_at:type_name -> google.protobuf.Timestamp
	25, // 18: truenow.query.TableSchema.updated_at:type_name -> google.protobuf.Timestamp
	23, // 19: truenow.query.FieldSchema.properties:type_name -> truenow.query.FieldSchema.PropertiesEntry
	18, // 20: truenow.query.QueryStatsResponse.top_queries:type_name -> truenow.query.TopQuery
	25, // 21: truenow.query.QueryStatsResponse.calculated_at:type_name -> google.protobuf.Timestamp
	24, // 22: truenow.query.QueryResult.RowEntry.value:type_name -> google.protobuf.Value
	1,  // 23: truenow.query.QueryService.ExecuteQuery:input_type -> truenow.query.QueryRequest
	1,  // 24: truenow.query.QueryService.StreamQuery:input_type -> truenow.query.QueryRequest
	9,  // 25: truenow.query.QueryService.ExplainQuery:input_type -> truenow.query.ExplainQueryRequest
	12, // 26: truenow.query.QueryService.GetSchema:input_type -> truenow.query.GetSchemaRequest
	16, // 27: truenow.query.QueryService.GetQueryStats:input_type -> truenow.query.GetQueryStatsRequest
	19, // 28: truenow.query.QueryService.CancelQuery:input_type -> truenow.query.CancelQueryRequest
	6,  // 29: truenow.query.QueryService.ExecuteQuery:output_type -> truenow.query.QueryResponse
	7,  // 30: truenow.query.QueryService.StreamQuery:output_type -> truenow.query.QueryResult
	10, // 31: truenow.query.QueryService.ExplainQuery:output_type -> truenow.query.ExplainQueryResponse
	13, // 32: truenow.query.QueryService.GetSchema:output_type -> truenow.query.GetSchemaResponse
	17, // 33: truenow.query.QueryService.GetQueryStats:output_type -> truenow.query.QueryStatsResponse
	20, // 34: truenow.query.QueryService.CancelQuery:output_type -> truenow.query.CancelQueryResponse
	29, // [29:35] is the sub-list for method output_type
	23, // [23:29] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		EnumInfos:         file_query_proto_enumTypes,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
